version: '3.9'
services:
  i2p:
    image: geti2p/i2p
    container_name: i2p_node
    environment:
      - JVM_XMX=1024m
    volumes:
      - i2phome:/i2p/.i2p
      - i2psnark:/i2psnark
    ports:
      - 4444:4444
      - 6668:6668
      - 7657:7657 
      - 54321:12345 
      - 54321:12345/udp